[target.x86_64-pc-windows-msvc]
rustflags = ["-C", "target-feature=+crt-static"]
[target.i686-pc-windows-msvc]
rustflags = ["-Ctarget-feature=+crt-static"]
[env]
LIBTORCH= { value = "tools/libtorch", relative = true }
REQ_DLL = "c10.dll,torch_cpu.dll,libiomp5md.dll,fbgemm.dll,uv.dll,asmjit.dll,MSVCP140.dll,VCRUNTIME140.dll,VCRUMTIME140_1.dll"